### ISSUE TITLE
calendar: manage mouse events in async notifications

### ISSUE THREAD

**Issue by copycat-killer** [copycat-killer/lain#289]
Same as #280

**Comment by aajjbb** [comment]
Weird fact: #280 still happens, even with this patch.

**Comment by copycat-killer** [comment]
Tell me how to reproduce then.

**Comment by aajjbb** [comment]
For me, just passes the mouse a few times in a widget attached by calendar. The notification will eventually be eternal (only hidding after a click).

**Comment by copycat-killer** [comment]
That's how I'm trying but I can't get it happen.

Why the `mouse::leave` should not happen, or not work? When the notification is on, the asynchronicity is gone. I need to investigate a little.

**Comment by copycat-killer** [comment]
@aajjbb Try adding  `calendar.id = nil` after `naughty.destroy` in `calendar.hide()`.

**Comment by copycat-killer** [comment]
@aajjbb Sorry to ping you, but can you still reproduce the issue?

**Comment by 2009** [comment]
I noticed that randomly my calendar will be shown.
It looks like it happens when I mouse over so fast it hasn't shown the notification by the time the "mouse:leave" signal is fired so it is ignored.

**Comment by poulpo** [comment]
@aajjbb 
Hi, I can confirm the problem is still on master right now. It appears only when the mouse enters and leaves the textbox quiet quickly.

**Comment by copycat-killer** [comment]
It should be fixed.

@aajjbb @2009 @poulpo Please give it a try: instead of being shown forever, it should timeout after 5 or `t_out` seconds.

**Comment by poulpo** [comment]
I'm afraid it is not fixed and neither it hide after X seconds. BTW, I use a Blackburn (with real minor modifications) theme on a dual screen.

**Comment by copycat-killer** [comment]
@poulpo How do you reproduce this? Are you able to do a video?

**Comment by poulpo** [comment]
@copycat-killer yes
https://share.jaguar-network.com/d9b55c68-227d-440b-b859-a6113a27403f
My screen delimitation is just after the clock display (but I do not think it has anything to do with this cause I can do the same with my 2nd screen clock).

**Comment by copycat-killer** [comment]
You also don't have the current day highlighted. Is that intentional, or another issue?

**Comment by yaast** [comment]
I can also confirm that this happens, sometimes when mouse passes fast by the widget that the calendar is attached to, it says there until you drag the mouse over again.
Not really sure how to reproduce it 100%.

**Comment by poulpo** [comment]
@copycat-killer 
I can reproduce it with the mouse pointer NOT leaving the left screen.
For the current date highlight, I now use the `/usr/bin/env TERM=linux /usr/bin/cal --color=always` trick and it work.

**Comment by copycat-killer** [comment]
I have to rethink about it again then.

Any help is welcome.

**Comment by poulpo** [comment]
@copycat-killer Well, with a little debugging I find that the `helpers.async(` in `calendar.update` function is inducing the problem.
When I reproduce the problem, I can see I enter `calendar.update` function (first lines), then I pass in the `calendar.hide` triggered by the `mouse::leave` signal, then the async part of `calendar.update` (making another hide() call and the naughty.notify that shows the calendar).

When there is no problem, the `calendar.update` function gets executed entirely (even the async part) before the `mouse::leave` signal is triggered.

I hope it's clear.

**Comment by poulpo** [comment]
And for the timeout, 0 being truthy in lua, `t_out or calendar.notification_preset.timeout or 5` is evaluated to 0 in the `calendar.show(0)` call.

**Comment by 2009** [comment]
The fs widget doens' t seem to have the problem, looks like it stores the last result from update in ```fs.notifications_presets.text``` and if the async is too slow it just shows whatever was returned by the last call to update.
Could we refactor the calendar to work like this too?

**Comment by copycat-killer** [comment]
> Could we refactor the calendar to work like this too?

We can for current month, but not for scroll/click switches.

**Comment by copycat-killer** [comment]
I made another attempt. Please test it.

**Comment by poulpo** [comment]
Original bug is still there, but now the calendar auto-hides after 5 seconds.

**Comment by copycat-killer** [comment]
@poulpo You mean the calendar auto-hides after 5 seconds **always**, or only when the bug appears?

Because in the second case, it's what I went for.

**Comment by 2009** [comment]
@copycat-killer It autohides when the bug appears for me.
Thanks!

**Comment by copycat-killer** [comment]
Now it should show up only when mouse is focusing one of the attached widgets.

Summoning all the people in this thread to test:  @aajjbb @2009 @poulpo @yaast

**Comment by poulpo** [comment]
@copycat-killer Fixed for me ! Thx !

**Comment by aajjbb** [comment]
It's working for me :+1:

**Comment by yaast** [comment]
Can confirm it works. Sorry for delayed response.
